### PR TITLE
Extend the range of exceptions IsSessionExpiredException accepts

### LINKED ISSUE #67: The current `SESSION_EXPIRED` mechanism is too rigid
The current `SESSION_EXPIRED` mechanism can only be triggered if a `retrofit2.HttpException` is thrown, therefore when using this library in combination with [`Retrofit-Error-Parsing`](https://github.com/halcyonmobile/retrofit-error-wrapping), which throws its own custom exception ([NetworkException](https://github.com/halcyonmobile/retrofit-error-wrapping/blob/master/error-parsing/src/main/java/com/halcyonmobile/errorparsing2/NetworkException.kt)), the `SESSION_EXPIRED` mechanism simply gets bypassed, resulting in the consumer not being informed about the incident (instead of being logged out, users would remain logged in and being shown errors for any attempt of accessing remote resources).

### PR DESCRIPTION
**Pull request by zsoltboldizsar**
PR meant to fix [68 ](https://github.com/halcyonmobile/retrofit-oauth2-helper/issues/67)

### CODE REVIEW

File: oauthgson/src/test/java/com/halcyonmobile/oauthmoshi/OauthRetrofitWithMoshiContainerBuilderTest.kt [hunk 1]
```diff
@@ -157,18 +157,21 @@ class OauthRetrofitWithGsonContainerBuilderTest {
             setResponseCode(400)
             setBody(REFRESH_RESPONSE)
         })
-        var caughtHttpException : HttpException? = null
+        var caughtHttpException: HttpException? = null
```
Comment (fknives) [inline oauthgson/src/test/java/com/halcyonmobile/oauthmoshi/OauthRetrofitWithMoshiContainerBuilderTest.kt:161]: with the API change this should be casted to HttpException also.

Because it's expected in the test that the expiration decider always returns true and we want to point where the issue is if the implementation doesn't match.

We should also introduce a test to usage of deprecated implementation

File: deploy.gradle [hunk 2]
```diff
@@ -2,5 +2,5 @@
 // ./gradlew howToPublish
 
 ext.libraryGroupId = 'oauth-setup'
-ext.libraryVersion = '1.0.2'
+ext.libraryVersion = '1.0.3'
```
Comment (fknives) [inline deploy.gradle:5]: Since this is intended as a minor release, it shouldn't contain breaking changes.

Will review the pull request on that assumption.

File: oauth/src/main/java/com/halcyonmobile/oauth/OauthRetrofitContainerBuilder.kt [hunk 3]
```diff
@@ -17,6 +17,7 @@
 package com.halcyonmobile.oauth
 
 import com.halcyonmobile.oauth.dependencies.AuthenticationLocalStorage
+import com.halcyonmobile.oauth.dependencies.IsSessionExpiredException
```
Comment (fknives) [inline oauth/src/main/java/com/halcyonmobile/oauth/OauthRetrofitContainerBuilder.kt:21]: This introduces a breaking change in the API.
I think it would be better to keep  the original class also and mark as Deprecated.
Also create another function in this class with the same name `setIsSessionExpiredExceptionDecider` deprecated.
We could import it as `import com.halcyonmobile.oauth.IsSessionExpiredException as DeprecatedIsSessionExpiredException`

Then if the deprecated method is used, we could use an Adapter:
The adapter extends the new IsSessionExpiredException and receives a DeprecatedIsSessionExpiredException as its constructor argument.
in invoke it checks if the throwable is HttpException && the deprecated returns true.

**Review by fknives — CHANGES_REQUESTED** [review]
The changes make sense, all my comments are about keeping the API backwards compatible.

Since the modifications shouldn't take long, I will modify the PR.

**Comment by zsoltboldizsar** [comment]
While it makes sense to maintain backwards compatibility, in this case I'd argue it does because: 
1. Consumers would want to get rid of workaround(s) from their codebases anyway and use the library as it was meant to be used. 
2. In my opinion API deprecation would make sense when an intended functionality gets replaced, not a workaround.

**Comment by fknives** [comment]
If it were true that someone only overwrote the `IsSessionExpiredException` because they were using the ErrorParser, I would agree.
However I don't think that is necessarily the case and I wouldn't want to break their code with import issues because of something they might not use.

**Edit:**
As far as I understand this PR and issue is opened to make the library more flexible so a solution can be implemented for the compatibility issue with ErrorParser more easily on client side or added natively. It doesn't solve the issue itself, session expiration would still be broken using default implementations of the libraries.

I think an issue should be also opened just for the compatibility with the ErrorParser. Not sure if it can be achieved natively in this library or the other should be modified, maybe both.

**Review by fknives — APPROVED** [review]

**Comment by zsoltboldizsar** [comment]
You understood it right, the purpose of this CL is to allow users who use this library in combination with [Retrofit-Error-Parsing](https://github.com/halcyonmobile/retrofit-error-wrapping) to add Retrofit-Error-Wrapping's own evaluator (see https://github.com/halcyonmobile/retrofit-error-wrapping/pull/44) which wouldn't bypass the current `SESSION_EXPIRED` mechanism. 

And yes, an issue has been opened in parallel to address this compatibility problem: https://github.com/halcyonmobile/retrofit-error-wrapping/issues/43 and ultimately to adjust the README according to this new change.
